### ISSUE TITLE
RuntimeError: expected scalar type Float but found Double

### ISSUE THREAD

**Issue by marvinquiet** [JinmiaoChenLab/scTM#5]
Dear Dr. Zhong,

Thank you for your great work in providing this great tool! I am very interested in your work and am trying it myself. However, I encountered the `RuntimeError: expected scalar type Float but found Double` when running `model.train(device="cuda:0")`. 

I was wondering if you have encountered the same problem before and any suggestions are greatly appreciated!

Sincerely,
Wenjing

**Comment by Chengwei94** [comment]
@marvinquiet,

I think it might have been something to do with your counts being double instead of float? Can you check its dtype?

**Comment by marvinquiet** [comment]
Dear Dr. Zhong,

Thank you for your reply. I have checked my input and the data type is numpy int64 prior to the model input. I was wondering if I need to perform some data preprocessing (e.g. log1p-norm, center scale) to turn it into `Float`?

Sincerely,
Wenjing

**Comment by Chengwei94** [comment]
@marvinquiet you don't need to scale and centre. Can you post the whole error message here?

**Comment by marvinquiet** [comment]
Sure, my anndata information is

```
AnnData object with n_obs Ã n_vars = 8062 Ã 22496
    obs: 'barcodes', 'nCount_RNA', 'nFeature_RNA', 'annotation', 'pixel_x', 'pixel_y', 'timepoint_numeric',
    var: 'genes'
    uns: 'spatial_neighbors'
    obsm: 'spatial'
    layers: 'count'
    obsp: 'spatial_connectivities', 'spatial_distances'
```

I am using the following codes to process the data:

```
# --- run STAMP
sq.gr.spatial_neighbors(adata, n_neighs=round(1 / 1000 * adata.n_obs))
sctm.seed.seed_everything(0)

model = sctm.stamp.STAMP(
    adata,
    n_topics=40,
    layer="count",
    time_covariate_keys="timepoint_numeric"
)

model.train(device="cuda:0")
```
I then encountered the following error:

```
Computing background frequencies
Computing background frequencies
Computing background frequencies
  0%|                                                                                                                  | 0/800 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/envs/SCTM_py38/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py", line 191, in __call__
    ret = self.fn(*args, **kwargs)
  File "/envs/SCTM_py38/lib/python3.8/site-packages/pyro/poutine/messenger.py", line 32, in _context_wrap
    return fn(*args, **kwargs)
  File "/envs/SCTM_py38/lib/python3.8/site-packages/pyro/poutine/messenger.py", line 32, in _context_wrap
    return fn(*args, **kwargs)
  File "/envs/SCTM_py38/lib/python3.8/site-packages/sctm/model.py", line 496, in model
    beta_gp = beta_gp_chole.matmul(beta_gp.unsqueeze(-1)).squeeze(
RuntimeError: expected scalar type Float but found Double

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_STAMP.py", line 91, in <module>
    model.train(device="cuda:0")
  File "/envs/SCTM_py38/lib/python3.8/site-packages/sctm/stamp.py", line 380, in train
    batch_loss = svi.step(
  File "/envs/SCTM_py38/lib/python3.8/site-packages/pyro/infer/svi.py", line 145, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/envs/SCTM_py38/lib/python3.8/site-packages/pyro/infer/trace_elbo.py", line 140, in loss_and_grads
    for model_trace, guide_trace in self._get_traces(model, guide, args, kwargs):
  File "/envs/SCTM_py38/lib/python3.8/site-packages/pyro/infer/elbo.py", line 237, in _get_traces
    yield self._get_trace(model, guide, args, kwargs)
  File "/envs/SCTM_py38/lib/python3.8/site-packages/pyro/infer/trace_mean_field_elbo.py", line 82, in _get_trace
    model_trace, guide_trace = super()._get_trace(model, guide, args, kwargs)
  File "/envs/SCTM_py38/lib/python3.8/site-packages/pyro/infer/trace_elbo.py", line 57, in _get_trace
    model_trace, guide_trace = get_importance_trace(
  File "/envs/SCTM_py38/lib/python3.8/site-packages/pyro/infer/enum.py", line 65, in get_importance_trace
    model_trace = poutine.trace(
  File "/envs/SCTM_py38/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py", line 216, in get_trace
    self(*args, **kwargs)
  File "/envs/SCTM_py38/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py", line 198, in __call__
    raise exc from e
  File "/envs/SCTM_py38/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py", line 191, in __call__
    ret = self.fn(*args, **kwargs)
  File "/envs/SCTM_py38/lib/python3.8/site-packages/pyro/poutine/messenger.py", line 32, in _context_wrap
    return fn(*args, **kwargs)
  File "/envs/SCTM_py38/lib/python3.8/site-packages/pyro/poutine/messenger.py", line 32, in _context_wrap
    return fn(*args, **kwargs)
  File "/envs/SCTM_py38/lib/python3.8/site-packages/sctm/model.py", line 496, in model
    beta_gp = beta_gp_chole.matmul(beta_gp.unsqueeze(-1)).squeeze(
RuntimeError: expected scalar type Float but found Double
                                     Trace Shapes:
                                      Param Sites:
                    stamp$$$caux_loc_unconstrained                    1
                  stamp$$$caux_scale_unconstrained                    1
              stamp$$$z_topic_lr_loc_unconstrained             40    40
            stamp$$$z_topic_lr_scale_unconstrained             40    40
            stamp$$$z_topic_diag_loc_unconstrained                    1
          stamp$$$z_topic_diag_scale_unconstrained                    1
                   stamp$$$delta_loc_unconstrained                22496
                 stamp$$$delta_scale_unconstrained                22496
                      stamp$$$bg_loc_unconstrained          22496     3
                    stamp$$$bg_scale_unconstrained          22496     3
                     stamp$$$tau_loc_unconstrained             40     1
                   stamp$$$tau_scale_unconstrained             40     1
                  stamp$$$lambda_loc_unconstrained             40 22496
                stamp$$$lambda_scale_unconstrained             40 22496
               stamp$$$batch_tau_loc_unconstrained             40     1
             stamp$$$batch_tau_scale_unconstrained             40     1
             stamp$$$batch_delta_loc_unconstrained              1 22496
           stamp$$$batch_delta_scale_unconstrained              1 22496
                    stamp$$$beta_loc_unconstrained             40 22496
                  stamp$$$beta_scale_unconstrained             40 22496
              stamp$$$beta_scale_loc_unconstrained             40 22496
            stamp$$$beta_scale_scale_unconstrained             40 22496
                    stamp$$$disp_loc_unconstrained                22496
                  stamp$$$disp_scale_unconstrained                22496
            stamp$$$z_topic_time_loc_unconstrained             40     3
          stamp$$$z_topic_time_scale_unconstrained             40     3
    stamp$$$z_topic_lr_timescale_loc_unconstrained             40    40
  stamp$$$z_topic_lr_timescale_scale_unconstrained             40    40
  stamp$$$z_topic_lr_lengthscale_loc_unconstrained             40     1
stamp$$$z_topic_lr_lengthscale_scale_unconstrained             40     1
     stamp$$$beta_gp_lengthscale_loc_unconstrained             40 22496
   stamp$$$beta_gp_lengthscale_scale_unconstrained             40 22496
              stamp$$$beta_gp_mu_loc_unconstrained             40 22496
            stamp$$$beta_gp_mu_scale_unconstrained             40 22496
                 stamp$$$beta_gp_loc_unconstrained       40 22496     3
               stamp$$$beta_gp_scale_unconstrained 40 22496     3     3
                     stamp$$$encoder.base.1.weight            128 44992
                       stamp$$$encoder.base.1.bias                  128
                     stamp$$$encoder.base.2.weight                  128
                       stamp$$$encoder.base.2.bias                  128
                  stamp$$$encoder.mu_topic.weight             40   128
                     stamp$$$encoder.mu_topic.bias                   40
                 stamp$$$encoder.norm_topic.0.bias                   40
                 stamp$$$encoder.norm_topic.1.bias                   40
                 stamp$$$encoder.norm_topic.2.bias                   40
                 stamp$$$encoder.diag_topic.weight             40   128
                   stamp$$$encoder.diag_topic.bias                   40
                                     Sample Sites:
                                       sample dist                    |
                                             value            256     |
                                         caux dist              1     |
                                             value              1     |
                                        delta dist          22496     |
                                             value          22496     |
                                           bg dist          22496     | 3
                                             value          22496     | 3
                                          tau dist       40     1     |
                                             value       40     1     |
                                      lambda_ dist       40 22496     |
                                             value       40 22496     |
                                 z_topic_diag dist              1     |
                                             value              1     |
                                   z_topic_lr dist       40    40     |
                                             value       40    40     |
                          beta_gp_lengthscale dist       40 22496     |
                                             value       40 22496     |
                                      beta_gp dist       40 22496     | 3
                                             value       40 22496     | 3
```

Please let me know if additional information is needed.

Thank you so much for your time!

Sincerely,
Wenjing

**Comment by OMIC-coding** [comment]
same problem~

**Comment by OMIC-coding** [comment]
Version:0.9 StartHTML:0000000499 EndHTML:0000439161 StartFragment:0000000535 EndFragment:0000439125 SourceURL:vscode-webview://0j0464lpu65dufvrg2d4s3dg7jnstapkkmotq8vdlcnp8ed4b982/index.html?id=4214f7ec-2946-481d-80e8-159a6965276f&origin=9ba698ed-244d-438d-9441-733128793371&swVersion=4&extensionId=&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&remoteAuthority=ssh-remote%2B10.128.249.202&purpose=notebookRenderer ---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/miniconda3/envs/stereo/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py in __call__(self, *args, **kwargs)
    190             try:
--> 191                 ret = self.fn(*args, **kwargs)
    192             except (ValueError, RuntimeError) as e:

~/miniconda3/envs/stereo/lib/python3.8/site-packages/pyro/poutine/messenger.py in _context_wrap(context, fn, *args, **kwargs)
     31     with context:
---> 32         return fn(*args, **kwargs)
     33 

~/miniconda3/envs/stereo/lib/python3.8/site-packages/pyro/poutine/messenger.py in _context_wrap(context, fn, *args, **kwargs)
     31     with context:
---> 32         return fn(*args, **kwargs)
     33 

~/miniconda3/envs/stereo/lib/python3.8/site-packages/sctm/model.py in model(self, x, sgc_x, categorical_covariate_code, time_covariate_code, not_cov, sample_idx, mask)
    495                         )
--> 496                         beta_gp = beta_gp_chole.matmul(beta_gp.unsqueeze(-1)).squeeze(
    497                             -1

RuntimeError: expected scalar type Float but found Double

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-82-a22b013e1f61> in <cell line: 18>()
     16 
     17 # We used a weighted sampler here as that the first timepoint is extremly small compared to the last timepoint.
---> 18 model.train(device="cuda:0", sampler = "W")

~/miniconda3/envs/stereo/lib/python3.8/site-packages/sctm/stamp.py in train(self, max_epochs, min_epochs, learning_rate, betas, not_cov_epochs, device, batch_size, sampler, weight_decay, iterations_to_anneal, min_kl, max_kl, early_stop, patience, shuffle, num_particles)
    378             # optimizer.zero_grad()
    379             for _, batch in enumerate(self.dataloader):
--> 380                 batch_loss = svi.step(
    381                     batch["x"].to(device),
    382                     batch["sgc_x"].to(device),

~/miniconda3/envs/stereo/lib/python3.8/site-packages/pyro/infer/svi.py in step(self, *args, **kwargs)
    143         # get loss and compute gradients
    144         with poutine.trace(param_only=True) as param_capture:
--> 145             loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
    146 
    147         params = set(

~/miniconda3/envs/stereo/lib/python3.8/site-packages/pyro/infer/trace_elbo.py in loss_and_grads(self, model, guide, *args, **kwargs)
    138         loss = 0.0
    139         # grab a trace from the generator
--> 140         for model_trace, guide_trace in self._get_traces(model, guide, args, kwargs):
    141             loss_particle, surrogate_loss_particle = self._differentiable_loss_particle(
    142                 model_trace, guide_trace

~/miniconda3/envs/stereo/lib/python3.8/site-packages/pyro/infer/elbo.py in _get_traces(self, model, guide, args, kwargs)
    235         else:
    236             for i in range(self.num_particles):
--> 237                 yield self._get_trace(model, guide, args, kwargs)

~/miniconda3/envs/stereo/lib/python3.8/site-packages/pyro/infer/trace_mean_field_elbo.py in _get_trace(self, model, guide, args, kwargs)
     80 
     81     def _get_trace(self, model, guide, args, kwargs):
---> 82         model_trace, guide_trace = super()._get_trace(model, guide, args, kwargs)
     83         if is_validation_enabled():
     84             _check_mean_field_requirement(model_trace, guide_trace)

~/miniconda3/envs/stereo/lib/python3.8/site-packages/pyro/infer/trace_elbo.py in _get_trace(self, model, guide, args, kwargs)
     55         against it.
     56         """
---> 57         model_trace, guide_trace = get_importance_trace(
     58             "flat", self.max_plate_nesting, model, guide, args, kwargs
     59         )

~/miniconda3/envs/stereo/lib/python3.8/site-packages/pyro/infer/enum.py in get_importance_trace(graph_type, max_plate_nesting, model, guide, args, kwargs, detach)
     63         if detach:
     64             guide_trace.detach_()
---> 65         model_trace = poutine.trace(
     66             poutine.replay(model, trace=guide_trace), graph_type=graph_type
     67         ).get_trace(*args, **kwargs)

~/miniconda3/envs/stereo/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py in get_trace(self, *args, **kwargs)
    214         Calls this poutine and returns its trace instead of the function's return value.
    215         """
--> 216         self(*args, **kwargs)
    217         return self.msngr.get_trace()

~/miniconda3/envs/stereo/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py in __call__(self, *args, **kwargs)
    196                 exc = exc_type("{}\n{}".format(exc_value, shapes))
    197                 exc = exc.with_traceback(traceback)
--> 198                 raise exc from e
    199             self.msngr.trace.add_node(
    200                 "_RETURN", name="_RETURN", type="return", value=ret

~/miniconda3/envs/stereo/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py in __call__(self, *args, **kwargs)
    189             )
    190             try:
--> 191                 ret = self.fn(*args, **kwargs)
    192             except (ValueError, RuntimeError) as e:
    193                 exc_type, exc_value, traceback = sys.exc_info()

~/miniconda3/envs/stereo/lib/python3.8/site-packages/pyro/poutine/messenger.py in _context_wrap(context, fn, *args, **kwargs)
     30 ) -> Any:
     31     with context:
---> 32         return fn(*args, **kwargs)
     33 
     34 

~/miniconda3/envs/stereo/lib/python3.8/site-packages/pyro/poutine/messenger.py in _context_wrap(context, fn, *args, **kwargs)
     30 ) -> Any:
     31     with context:
---> 32         return fn(*args, **kwargs)
     33 
     34 

~/miniconda3/envs/stereo/lib/python3.8/site-packages/sctm/model.py in model(self, x, sgc_x, categorical_covariate_code, time_covariate_code, not_cov, sample_idx, mask)
    494                             ).to_event(1),
    495                         )
--> 496                         beta_gp = beta_gp_chole.matmul(beta_gp.unsqueeze(-1)).squeeze(
    497                             -1
    498                         ) + bg[None, ...].expand(self.n_topics, -1, self.n_time)

RuntimeError: expected scalar type Float but found Double
                                     Trace Shapes:                      
                                      Param Sites:                      
                    stamp$$$caux_loc_unconstrained                  1   
                  stamp$$$caux_scale_unconstrained                  1   
              stamp$$$z_topic_lr_loc_unconstrained           40    40   
            stamp$$$z_topic_lr_scale_unconstrained           40    40   
            stamp$$$z_topic_diag_loc_unconstrained                  1   
          stamp$$$z_topic_diag_scale_unconstrained                  1   
                   stamp$$$delta_loc_unconstrained               6000   
                 stamp$$$delta_scale_unconstrained               6000   
                      stamp$$$bg_loc_unconstrained         6000    12   
                    stamp$$$bg_scale_unconstrained         6000    12   
                     stamp$$$tau_loc_unconstrained           40     1   
                   stamp$$$tau_scale_unconstrained           40     1   
                  stamp$$$lambda_loc_unconstrained           40  6000   
                stamp$$$lambda_scale_unconstrained           40  6000   
               stamp$$$batch_tau_loc_unconstrained           40     1   
             stamp$$$batch_tau_scale_unconstrained           40     1   
             stamp$$$batch_delta_loc_unconstrained            1  6000   
           stamp$$$batch_delta_scale_unconstrained            1  6000   
                    stamp$$$beta_loc_unconstrained           40  6000   
                  stamp$$$beta_scale_unconstrained           40  6000   
              stamp$$$beta_scale_loc_unconstrained           40  6000   
            stamp$$$beta_scale_scale_unconstrained           40  6000   
                    stamp$$$disp_loc_unconstrained               6000   
                  stamp$$$disp_scale_unconstrained               6000   
            stamp$$$z_topic_time_loc_unconstrained           40    12   
          stamp$$$z_topic_time_scale_unconstrained           40    12   
    stamp$$$z_topic_lr_timescale_loc_unconstrained           40    40   
  stamp$$$z_topic_lr_timescale_scale_unconstrained           40    40   
  stamp$$$z_topic_lr_lengthscale_loc_unconstrained           40     1   
stamp$$$z_topic_lr_lengthscale_scale_unconstrained           40     1   
     stamp$$$beta_gp_lengthscale_loc_unconstrained           40  6000   
   stamp$$$beta_gp_lengthscale_scale_unconstrained           40  6000   
              stamp$$$beta_gp_mu_loc_unconstrained           40  6000   
            stamp$$$beta_gp_mu_scale_unconstrained           40  6000   
                 stamp$$$beta_gp_loc_unconstrained      40 6000    12   
               stamp$$$beta_gp_scale_unconstrained 40 6000   12    12   
                     stamp$$$encoder.base.1.weight          128 12000   
                       stamp$$$encoder.base.1.bias                128   
                     stamp$$$encoder.base.2.weight                128   
                       stamp$$$encoder.base.2.bias                128   
                   stamp$$$encoder.mu_topic.weight           40   128   
                     stamp$$$encoder.mu_topic.bias                 40   
                 stamp$$$encoder.norm_topic.0.bias                 40   
                 stamp$$$encoder.norm_topic.1.bias                 40   
                 stamp$$$encoder.norm_topic.2.bias                 40   
                 stamp$$$encoder.norm_topic.3.bias                 40   
                 stamp$$$encoder.norm_topic.4.bias                 40   
                 stamp$$$encoder.norm_topic.5.bias                 40   
                 stamp$$$encoder.norm_topic.6.bias                 40   
                 stamp$$$encoder.norm_topic.7.bias                 40   
                 stamp$$$encoder.norm_topic.8.bias                 40   
                 stamp$$$encoder.norm_topic.9.bias                 40   
                stamp$$$encoder.norm_topic.10.bias                 40   
                stamp$$$encoder.norm_topic.11.bias                 40   
                 stamp$$$encoder.diag_topic.weight           40   128   
                   stamp$$$encoder.diag_topic.bias                 40   
                                     Sample Sites:                      
                                       sample dist                  |   
                                             value          256     |   
                                         caux dist            1     |   
                                             value            1     |   
                                        delta dist         6000     |   
                                             value         6000     |   
                                           bg dist         6000     | 12
                                             value         6000     | 12
                                          tau dist      40    1     |   
                                             value      40    1     |   
                                      lambda_ dist      40 6000     |   
                                             value      40 6000     |   
                                 z_topic_diag dist            1     |   
                                             value            1     |   
                                   z_topic_lr dist      40   40     |   
                                             value      40   40     |   
                          beta_gp_lengthscale dist      40 6000     |   
                                             value      40 6000     |   
                                      beta_gp dist      40 6000     | 12
                                             value      40 6000     | 12

**Comment by marvinquiet** [comment]
Just a quick update: I have changed my `time_covariate_keys` to `np.float32`, my `adata.layers['count']` to `np.float64`, and used `sctm.pp.filter_genes(adata, 0.05)` to successfully run STAMP on my data.
